/**
 * 
 */
package com.springtour.otg.infrastructure.channel.icbc;

import static org.junit.Assert.*;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import org.junit.Before;
import org.junit.Test;

import cn.com.infosec.icbc.ReturnValue;

import com.springtour.otg.application.util.Configurations;
import com.springtour.otg.domain.model.merchant.Merchant;
import com.springtour.otg.domain.model.transaction.Transaction;
import com.springtour.otg.domain.model.transaction.TransactionNo;
import com.springtour.otg.domain.shared.Money;

/**
 * @author 005073
 * 
 */

public class IcbcRequestUrlAssemblerUnitTests {
	private IcbcRequestUrlAssembler assembler;
	private static final String ip = "180.168.15.70";
	private static final String url = "http://180.168.15.70/pay/payresult";
	private Transaction transaction = new Transaction();
	private static final String expectedUrl = "https://mybank.dccnet.com.cn/servlet/NewB2cMerPayReqServlet?interfaceName=ICBC_PERBANK_B2C&interfaceVersion=1.0.0.11&tranData=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iR0JLIiBzdGFuZGFsb25lPSJubyI/PjxCMkNSZXE+CiAgPGludGVyZmFjZU5hbWU+SUNCQ19QRVJCQU5LX0IyQzwvaW50ZXJmYWNlTmFtZT4KICA8aW50ZXJmYWNlVmVyc2lvbj4xLjAuMC4xMTwvaW50ZXJmYWNlVmVyc2lvbj4KICA8b3JkZXJJbmZvPgogICAgPG9yZGVyRGF0ZT4yMDEzMDkyMjE1MDUwNTwvb3JkZXJEYXRlPgogICAgPGN1clR5cGU+MDAxPC9jdXJUeXBlPgogICAgPG1lcklEPjEwMDFFQzIzODI4NzYxPC9tZXJJRD4KICAgIDxzdWJPcmRlckluZm9MaXN0PgogICAgICA8c3ViT3JkZXJJbmZvPgogICAgICAgIDxvcmRlcmlkPjIwMTMwNzIyMTIzNDEyMTk8L29yZGVyaWQ+CiAgICAgICAgPGFtb3VudD4xMDA8L2Ftb3VudD4KICAgICAgICA8aW5zdGFsbG1lbnRUaW1lcz4xPC9pbnN0YWxsbWVudFRpbWVzPgogICAgICAgIDxtZXJBY2N0PjEwMDEyMjM2MDkwMDQ2NDEwNjY8L21lckFjY3Q+CiAgICAgICAgPGdvb2RzSUQ+PC9nb29kc0lEPgogICAgICAgIDxnb29kc05hbWU+tLrH78LD086y+sa3PC9nb29kc05hbWU+CiAgICAgICAgPGdvb2RzTnVtPjwvZ29vZHNOdW0+CiAgICAgICAgPGNhcnJpYWdlQW10PjwvY2FycmlhZ2VBbXQ+CiAgICAgIDwvc3ViT3JkZXJJbmZvPgogICAgPC9zdWJPcmRlckluZm9MaXN0PgogIDwvb3JkZXJJbmZvPgogIDxjdXN0b20+CiAgICA8dmVyaWZ5Sm9pbkZsYWc+MDwvdmVyaWZ5Sm9pbkZsYWc+CiAgICA8TGFuZ3VhZ2U+WkhfQ048L0xhbmd1YWdlPgogIDwvY3VzdG9tPgogIDxtZXNzYWdlPgogICAgPGNyZWRpdFR5cGU+MjwvY3JlZGl0VHlwZT4KICAgIDxub3RpZnlUeXBlPkhTPC9ub3RpZnlUeXBlPgogICAgPHJlc3VsdFR5cGU+MDwvcmVzdWx0VHlwZT4KICAgIDxtZXJSZWZlcmVuY2U+PC9tZXJSZWZlcmVuY2U+CiAgICA8bWVyQ3VzdG9tSXA+MTgwLjE2OC4xNS43MDwvbWVyQ3VzdG9tSXA+CiAgICA8Z29vZHNUeXBlPjwvZ29vZHNUeXBlPgogICAgPG1lckN1c3RvbUlEPjwvbWVyQ3VzdG9tSUQ+CiAgICA8bWVyQ3VzdG9tUGhvbmU+PC9tZXJDdXN0b21QaG9uZT4KICAgIDxnb29kc0FkZHJlc3M+PC9nb29kc0FkZHJlc3M+CiAgICA8bWVyT3JkZXJSZW1hcms+PC9tZXJPcmRlclJlbWFyaz4KICAgIDxtZXJIaW50PjwvbWVySGludD4KICAgIDxyZW1hcmsxPjwvcmVtYXJrMT4KICAgIDxyZW1hcmsyPjwvcmVtYXJrMj4KICAgIDxtZXJVUkw+aHR0cDovLzE5Mi4xNjguOTkuMTUwOjgwL0RlZmF1bHQuanNwPC9tZXJVUkw+CiAgICA8bWVyVkFSPjwvbWVyVkFSPgogIDwvbWVzc2FnZT4KPC9CMkNSZXE+&merSignMsg=M68XBZE47XATSh9SeMYGIZNA0JWJX+v6M0jYGgjoI3hdZCTL5I4LRYdWkGCXgygxMU4Yr+RTWCDH3P1HJE/Et1R2Pm6NimAU0LxJkmxR0x/EGEBj+by53sBKteK55ZvqP/5PSGsGB3NgqTx4ppjbz8zMyvLAqsnys+NRVSmfcJc=&merCert=MIIDFDCCAfygAwIBAgIKG5LKECVWAAIyizANBgkqhkiG9w0BAQUFADA7MR8wHQYDVQQDExZJQ0JDIFRlc3QgQ29ycG9yYXRlIENBMRgwFgYDVQQKEw90ZXN0aWNiYy5jb20uY24wHhcNMTMwOTIwMDcxODEzWhcNMTQwOTIwMDcxODEzWjBIMR0wGwYDVQQDExRjaHVucWl1MTMwNzE5LmUuMTAwMTENMAsGA1UECxMEMTAwMTEYMBYGA1UEChMPdGVzdGljYmMuY29tLmNuMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVXxHrevCPT88B0bvow4yqJ7SsRDywxDAziJ+uvbWN9lk35GAfHnaM4LysLHs6b7OuOpacVQ7aEDNmn66Ersk7JT2nB7ucQlcpff2mvZXRuw0sBl6/rXmVDd+HQvkoyEQRWRawSiLXpmlFTHRfVif/tc7j8LjGOjLz7yx904fZmQIDAQABo4GQMIGNMB8GA1UdIwQYMBaAFER9t5AsN6TZ7WzipIdXZwq18E0UMEsGA1UdHwREMEIwQKA+oDykOjA4MQ4wDAYDVQQDEwVjcmwyOTEMMAoGA1UECxMDY3JsMRgwFgYDVQQKEw90ZXN0aWNiYy5jb20uY24wHQYDVR0OBBYEFOqerfD1NwEQYflKDXp18Ej6UYwMMA0GCSqGSIb3DQEBBQUAA4IBAQA5fCzhJ6zHphR4HVJTA0ib4YEIVukPaoRSNqUSRHRfWKMUTICsGzo+oelR6Z8of3U8DPe4QwbPYlJkWy5EIaDvctzWpAe/I9PCXZHVLakDwbSuuVUUlf+IwGQ1Cvl6Un4oK5jIhB+NoMvcvZGX8IeiXtTkjKi77Ewldwa5Po97HmouaR3gcA+pdBuuoPu+6Ni6daYGoBwPk5pMI4VM1i2RRZ7EXIh4Yhogr2Yv0GJTarKbxdGpW95hmV+HSan7VqDNYjTAixBPEGECP/dUReTPvGdQXGkYrnFCg8RScifrg55iY3H22ynftAbpFGXSR3FF586n63wmbmQ2miLQtGWR";

	@Before
	public void prepare() throws ParseException {
		assembler = new IcbcRequestUrlAssembler();
		Encryption encryption = new Encryption();
		Configurations configurations = new Configurations();
		configurations
				.setIcbcPayRequestUrl("https://mybank.dccnet.com.cn/servlet/NewB2cMerPayReqServlet");
		configurations.setIcbcCertFileName("icbcPubCert.crt");
		configurations.setIcbcKeyFileName("icbcPrivateKey.key");
		encryption.setConfigurations(configurations);
		assembler.setEncryption(encryption);
		assembler.setConfigurations(configurations);
		transaction.setMerchantCode("1001223609004631160");
		transaction.setTransactionNo(new TransactionNo("20130826349822191"));
		transaction.setAmount(Money.valueOf(BigDecimal.ONE));
		transaction.setMerchant(new Merchant("", null, "",
				"1001223609004631160", "1001EC23837830,12345678"));
		 SimpleDateFormat sFormat = new SimpleDateFormat("HHmmss");
		String time = "20130730"+sFormat.format(Calendar.getInstance().getTime());
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(
				"yyyyMMddHHmmss");
		transaction.setWhenRequested(simpleDateFormat.parse(time));
	}

	@Test
	public void generateUrl() {
		String rurl = assembler.assembleUrl(transaction, url, ip);
		System.out.println(rurl);
		assertNotNull(rurl);
		//System.out.println(expectedUrl);
		//assertTrue(rurl.equals(expectedUrl));
		
		//System.out.println(new String(ReturnValue.base64dec("PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iR0JLIiBzdGFuZGFsb25lPSJubyI/PjxCMkNSZXE+CiAgPGludGVyZmFjZU5hbWU+SUNCQ19QRVJCQU5LX0IyQzwvaW50ZXJmYWNlTmFtZT4KICA8aW50ZXJmYWNlVmVyc2lvbj4xLjAuMC4xMTwvaW50ZXJmYWNlVmVyc2lvbj4KICA8b3JkZXJJbmZvPgogICAgPG9yZGVyRGF0ZT4yMDEzMDkyMjE1MDUwNTwvb3JkZXJEYXRlPgogICAgPGN1clR5cGU+MDAxPC9jdXJUeXBlPgogICAgPG1lcklEPjEwMDFFQzIzODI4NzYxPC9tZXJJRD4KICAgIDxzdWJPcmRlckluZm9MaXN0PgogICAgICA8c3ViT3JkZXJJbmZvPgogICAgICAgIDxvcmRlcmlkPjIwMTMwNzIyMTIzNDEyMTk8L29yZGVyaWQ+CiAgICAgICAgPGFtb3VudD4xMDA8L2Ftb3VudD4KICAgICAgICA8aW5zdGFsbG1lbnRUaW1lcz4xPC9pbnN0YWxsbWVudFRpbWVzPgogICAgICAgIDxtZXJBY2N0PjEwMDEyMjM2MDkwMDQ2NDEwNjY8L21lckFjY3Q+CiAgICAgICAgPGdvb2RzSUQ+PC9nb29kc0lEPgogICAgICAgIDxnb29kc05hbWU+5pil56eL5peF5ri45Lqn5ZOBPC9nb29kc05hbWU+CiAgICAgICAgPGdvb2RzTnVtPjwvZ29vZHNOdW0+CiAgICAgICAgPGNhcnJpYWdlQW10PjwvY2FycmlhZ2VBbXQ+CiAgICAgIDwvc3ViT3JkZXJJbmZvPgogICAgPC9zdWJPcmRlckluZm9MaXN0PgogIDwvb3JkZXJJbmZvPgogIDxjdXN0b20+CiAgICA8dmVyaWZ5Sm9pbkZsYWc+MDwvdmVyaWZ5Sm9pbkZsYWc+CiAgICA8TGFuZ3VhZ2U+WkhfQ048L0xhbmd1YWdlPgogIDwvY3VzdG9tPgogIDxtZXNzYWdlPgogICAgPGNyZWRpdFR5cGU+MjwvY3JlZGl0VHlwZT4KICAgIDxub3RpZnlUeXBlPkhTPC9ub3RpZnlUeXBlPgogICAgPHJlc3VsdFR5cGU+MDwvcmVzdWx0VHlwZT4KICAgIDxtZXJSZWZlcmVuY2U+PC9tZXJSZWZlcmVuY2U+CiAgICA8bWVyQ3VzdG9tSXA+MTgwLjE2OC4xNS43MDwvbWVyQ3VzdG9tSXA+CiAgICA8Z29vZHNUeXBlPjwvZ29vZHNUeXBlPgogICAgPG1lckN1c3RvbUlEPjwvbWVyQ3VzdG9tSUQ+CiAgICA8bWVyQ3VzdG9tUGhvbmU+PC9tZXJDdXN0b21QaG9uZT4KICAgIDxnb29kc0FkZHJlc3M+PC9nb29kc0FkZHJlc3M+CiAgICA8bWVyT3JkZXJSZW1hcms+PC9tZXJPcmRlclJlbWFyaz4KICAgIDxtZXJIaW50PjwvbWVySGludD4KICAgIDxyZW1hcmsxPjwvcmVtYXJrMT4KICAgIDxyZW1hcmsyPjwvcmVtYXJrMj4KICAgIDxtZXJVUkw+aHR0cDovLzE5Mi4xNjguOTkuMTUwOjgwL0RlZmF1bHQuanNwPC9tZXJVUkw+CiAgICA8bWVyVkFSPjwvbWVyVkFSPgogIDwvbWVzc2FnZT4KPC9CMkNSZXE+".getBytes())));
		//System.out.println(new String(ReturnValue.base64dec("PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iR0JLIiBzdGFuZGFsb25lPSJubyI/PjxCMkNSZXE+CiAgPGludGVyZmFjZU5hbWU+SUNCQ19QRVJCQU5LX0IyQzwvaW50ZXJmYWNlTmFtZT4KICA8aW50ZXJmYWNlVmVyc2lvbj4xLjAuMC4xMTwvaW50ZXJmYWNlVmVyc2lvbj4KICA8b3JkZXJJbmZvPgogICAgPG9yZGVyRGF0ZT4yMDEzMDkyMjE1MDUwNTwvb3JkZXJEYXRlPgogICAgPGN1clR5cGU+MDAxPC9jdXJUeXBlPgogICAgPG1lcklEPjEwMDFFQzIzODI4NzYxPC9tZXJJRD4KICAgIDxzdWJPcmRlckluZm9MaXN0PgogICAgICA8c3ViT3JkZXJJbmZvPgogICAgICAgIDxvcmRlcmlkPjIwMTMwNzIyMTIzNDEyMTk8L29yZGVyaWQ+CiAgICAgICAgPGFtb3VudD4xMDA8L2Ftb3VudD4KICAgICAgICA8aW5zdGFsbG1lbnRUaW1lcz4xPC9pbnN0YWxsbWVudFRpbWVzPgogICAgICAgIDxtZXJBY2N0PjEwMDEyMjM2MDkwMDQ2NDEwNjY8L21lckFjY3Q+CiAgICAgICAgPGdvb2RzSUQ+PC9nb29kc0lEPgogICAgICAgIDxnb29kc05hbWU+tLrH78LD086y+sa3PC9nb29kc05hbWU+CiAgICAgICAgPGdvb2RzTnVtPjwvZ29vZHNOdW0+CiAgICAgICAgPGNhcnJpYWdlQW10PjwvY2FycmlhZ2VBbXQ+CiAgICAgIDwvc3ViT3JkZXJJbmZvPgogICAgPC9zdWJPcmRlckluZm9MaXN0PgogIDwvb3JkZXJJbmZvPgogIDxjdXN0b20+CiAgICA8dmVyaWZ5Sm9pbkZsYWc+MDwvdmVyaWZ5Sm9pbkZsYWc+CiAgICA8TGFuZ3VhZ2U+WkhfQ048L0xhbmd1YWdlPgogIDwvY3VzdG9tPgogIDxtZXNzYWdlPgogICAgPGNyZWRpdFR5cGU+MjwvY3JlZGl0VHlwZT4KICAgIDxub3RpZnlUeXBlPkhTPC9ub3RpZnlUeXBlPgogICAgPHJlc3VsdFR5cGU+MDwvcmVzdWx0VHlwZT4KICAgIDxtZXJSZWZlcmVuY2U+PC9tZXJSZWZlcmVuY2U+CiAgICA8bWVyQ3VzdG9tSXA+MTgwLjE2OC4xNS43MDwvbWVyQ3VzdG9tSXA+CiAgICA8Z29vZHNUeXBlPjwvZ29vZHNUeXBlPgogICAgPG1lckN1c3RvbUlEPjwvbWVyQ3VzdG9tSUQ+CiAgICA8bWVyQ3VzdG9tUGhvbmU+PC9tZXJDdXN0b21QaG9uZT4KICAgIDxnb29kc0FkZHJlc3M+PC9nb29kc0FkZHJlc3M+CiAgICA8bWVyT3JkZXJSZW1hcms+PC9tZXJPcmRlclJlbWFyaz4KICAgIDxtZXJIaW50PjwvbWVySGludD4KICAgIDxyZW1hcmsxPjwvcmVtYXJrMT4KICAgIDxyZW1hcmsyPjwvcmVtYXJrMj4KICAgIDxtZXJVUkw+aHR0cDovLzE5Mi4xNjguOTkuMTUwOjgwL0RlZmF1bHQuanNwPC9tZXJVUkw+CiAgICA8bWVyVkFSPjwvbWVyVkFSPgogIDwvbWVzc2FnZT4KPC9CMkNSZXE+".getBytes())));
	}
}
